### ISSUE TITLE
Maximum amount in the treasury is continuously earning interest

### ISSUE THREAD

**Issue by kimidesu** [noizu/public-bladeofeternity.com#157]
Reporter:	Judgement [18633]
Submission Date:	October 24, 2015 04:41:08
>Treasury issue noticed -- I had max treasury amount plus interest ( 206,000,000) in account at reset. When I logged in today it showed I had 212,180,000 in treasury. 

Reporter:	Big Boss [19677]
Submission Date:	October 27, 2015 11:36:10
>Treasury Interest is playing up. -- The interest rate on the treasury seems to be playing up. 
I banked my 6mil interest the other day, only to come back a few days later and find I have 12 180 000 instead of 6mil. I banked it and paid no heed at first, then it happened again a few days later and also found it again today. And it's been that 12mil figure every time.
I didn't have any items or Crystals on the market either so it seems to be an interest problem.

**Comment by kimidesu** [comment]
>Quasimodo: Are others being paid interest even when they have more than $200M? If yes, was this change intentional? 
Gargoyle: yup but only to 212mil 
King Believe II: If treasury has more than $200 mil at reset no interest is awarded.

**Comment by noizu** [comment]
I tweaked the logic. They won't receive interest over a specific cap but
can still receive interest on top of 200,000.
