### ISSUE TITLE
Changing the player name does not display the updated name on the Online Users page

### ISSUE THREAD

**Issue by kimidesu** [noizu/public-bladeofeternity.com#171]
From: [?] SolaPyre [19,750] 
Sent at: February 22, 2016, 7:44:08 pm

> I changed my name to SolaPyre but it didn't change in the online users list. It has changed everywhere else tho. Is it a glitch or does it take longer for the list to catch up? 

Expected Outcome:
The Online Users page should display the updated player name and not the old player name.

Outcome:
The Online Users page was still displaying Tarren	[19,750] though on the Users page, the change was already applied.

**Comment by noizu** [comment]
Its cached for performance. It will update after a day. Not a bug.
